jwt.secret: ${GENERATED_KEY}
server.port: 1337


spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://192.168.1.56:5432/website-backend?currentSchema=public
    username: website-backend-user
    password: website-backend-user
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

#drop n create table again, good for testing, comment this in production
#spring.jpa.hibernate.ddl-auto=create