version: 2
jobs:
  build:
    working_directory: ~/website-backend

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - restore_cache:
          key: website-backend-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: website-backend-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_artifacts:
          path: target/website-backend.war

  deploy:
    machine:
      enabled: true
    working_directory: ~/website-backend

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "18:4a:ef:50:fe:1d:95:d6:a3:4f:bb:09:85:4e:4f:36"
      - run:
          name: Deploy with SCP
          command: |
            scp target/website-backend.war $SSH_USER@$SSH_HOST:/var/lib/tomcat8/webapps/website-backend.war

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build