version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: mvn-dependencies-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: mvn-dependencies-{{ checksum "pom.xml" }}

      - run: mvn package

      # need unique id to link this cache to deploy step, such that no rebuild is needed.
      # it's however not possible to use environment variables in cache-key names, so have to save it to file first
      - run: echo "$CIRCLE_WORKFLOW_ID" > _env_var_holder

      - save_cache:
          paths: # cache artifact so it can be retrieved in deploy step, instead of building again.
            - ~/repo/target/website-backend.war
            - ~/repo/Dockerfile
            - ~/repo/docker-compose.yml
            - ~/repo/run.sh
          key: backend-artifact-{{ checksum "_env_var_holder" }}

  deploy:
    machine: true

    working_directory: ~/repo

    steps:
      - run: echo "$CIRCLE_WORKFLOW_ID" > _env_var_holder

      - restore_cache:
          keys:
            - backend-artifact-{{ checksum "_env_var_holder" }}

      - add_ssh_keys:
          fingerprints:
            - "5b:01:54:2b:8b:cc:57:20:c0:be:2c:24:f6:22:18:81"

      - run: scp -rq -o stricthostkeychecking=no ./* $SSH_USER@$SSH_HOST:~/backend/
      - run: ssh $SSH_USER@$SSH_HOST "cd ~/backend && chmod 700 run.sh && ./run.sh"

workflows:
  version: 2
  package-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
