version: 2
jobs:
  build:
    working_directory: ~/website-backend

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - restore_cache:
          key: website-backend-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: website-backend-{{ checksum "pom.xml" }}

      - run: mvn package

      - add_ssh_keys:
          fingerprints:
            - "64:36:b1:01:c9:44:1a:45:68:33:e4:68:7c:39:9f:b6"
      - run: scp -o stricthostkeychecking=no target/website-backend.war $SSH_USER@$SSH_HOST:/var/lib/tomcat8/webapps/website-backend.war
