version: 2
jobs:
  build:
    working_directory: ~/website-backend

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - restore_cache:
          key: website-backend-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: website-backend-{{ checksum "pom.xml" }}

      - run: mvn package

      - add_ssh_keys:
          fingerprints:
            - "18:4a:ef:50:fe:1d:95:d6:a3:4f:bb:09:85:4e:4f:36"
      - run: scp target/website-backend.war $SSH_USER@$SSH_HOST:/var/lib/tomcat8/webapps/website-backend.war
