version: '3'

services:
  app-container:
    container_name: website-backend
    image: website-backend:1.0
    environment:
      GENERATED_KEY: ${GENERATED_KEY}
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    deploy:
      restart_policy:
        condition: any
        delay: 15s     
        max_attempts: 10
        window: 500s
